### ISSUE TITLE
[BUG] Cozy Player - Error on the browser console, but the module seem to work fine

### ISSUE THREAD

**Issue by p4535992** [psyny/FoundryVTT#6]
**Detail of the world:**

Foundry Virtual Tabletop, version 0.6.5
System Core: Dungeons and Dragons 5th Edition, version 0.93
Modules Installed:  Cozy Player, version 1.3.0

**Description of the issue:**

There is a error when i hover a token and make appear your popout on the browser console, it's seem caused from a javascript file of your module, but the module it's seem continue to work fine, at least for me, but maybe is better look out?

![Image](https://i.imgur.com/mHw8nM6.jpg)

Sorry for the poor thecnical details.

**Comment by psyny** [comment]
Thanks very much for the report! =)

Fixed this on version 1.3.1.
