### ISSUE TITLE
Token overlay appearing erroneously on game launch

### ISSUE THREAD

**Issue by joshjlewis93** [psyny/FoundryVTT#8]
Every time I launch a game with the plugin enabled, one of the tokens will display its overlay as if it's been moused over, and it won't disappear until I actually hover my mouse over it and then move it away again. It works fine afterwards, it's just the very first instance that occurs by itself for some reason.

**Comment by psyny** [comment]
Thanks very much for the report! =)

Fixed this on version 1.3.1.
